const InputDataCompany = [
    {
        name: "companyName",
        placeHolder: "Your Company*",
        type:"text",
        value:"",
        fontLg: true,
        required: true,
    },
    {
        name: "name",
        placeHolder: "Your Firts and Last Name",
        type:"text",
        value:"",
        fontLg: false,
        required: true,
    },
    {
        name: "companyWebsite",
        placeHolder: "Company Website*",
        type:"url",
        value:"",
        fontLg: false,
        required: true,
    },
    {
        name: "companyAddress",
        placeHolder: "Company Address",
        type:"text",
        value:"",
        fontLg: false,
        required: false,
    },
    {
        name: "companyCity",
        placeHolder: "City, State ZIP",
        type:"text",
        value:"",
        fontLg: false,
        required: false,
    },
    {
        name: "companyContry",
        placeHolder: "Contry",
        type:"text",
        value:"",
        fontLg: false,
        required: false,
    },
    {
        name: "companyPhone",
        placeHolder: "Phone No.*",
        type:"tel",
        value:"",
        fontLg: false,
        required: true,
    },
    {
        name: "companyEmail",
        placeHolder: "Email Adress*",
        type:"tel",
        value:"",
        fontLg: false,
        required: true,
    },
];

export default InputDataCompany;
